### ISSUE TITLE
Runtime assertion in do_shadow_LoadG failed

### ISSUE THREAD

**Issue by wmkhoo** [wmkhoo/taintgrind#14]
Taintgrind: the 'impossible' happened:
   do_shadow_LoadG

host stacktrace:
==17973==    at 0x5802E1CD: show_sched_status_wrk (m_libcassert.c:355)
==17973==    by 0x5802E2E4: report_and_quit (m_libcassert.c:426)
==17973==    by 0x5802E584: vgPlain_tool_panic (m_libcassert.c:502)
==17973==    by 0x5801EF13: vgTaintgrind_instrument (tnt_translate.c:5633)
==17973==    by 0x580491B1: tool_instrument_then_gdbserver_if_needed (m_translate.c:239)
==17973==    by 0x580F6DAE: LibVEX_FrontEnd (main_main.c:648)
==17973==    by 0x580F75BB: LibVEX_Translate (main_main.c:1173)
==17973==    by 0x5804B713: vgPlain_translate (m_translate.c:1794)
==17973==    by 0x58081286: vgPlain_scheduler (scheduler.c:1056)
==17973==    by 0x5809062A: run_a_thread_NORETURN (syswrap-linux.c:103)

Credit: Reported by Giuseppe Di Guglielmo

**Comment by GiuseppeDiGuglielmo** [comment]
This fixes the issue thank you!
