### ISSUE TITLE
VG_USERREQ__TAINTGRIND_ALLOWSYSCALL misses  '_'  in taintgrind.h ? 

### ISSUE THREAD

**Issue by JodieAllen** [wmkhoo/taintgrind#24]
Hi,
In taintgrind.h , `VG_USERREQ__TAINTGRIND_ALLOW_SYSCALL` is defined as following:
```
typedef enum {
.....
VG_USERREQ__TAINTGRIND_ALLOW_SYSCALL,
.......
```
However, it is used as following:
```
#define TNT_ALLOW_SYSCALL(syscallno) \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_ALLOWSYSCALL,syscallno,0,0,0,0);
```
`VG_USERREQ__TAINTGRIND_ALLOWSYSCALL` is missing '_' between 'ALLOW' and 'SYSCALL'.
And can you give me some advice where I can find the explanation of function `TNT_ALLOW_SYSCALL`, because I want to know the aim of this function is tracing taint in syscalls or it does other jobs.

Thank you very much!

**Comment by wmkhoo** [comment]
That feature is currently not being actively developed.
What are you trying to do/accomplish?
