### ISSUE TITLE
How to track a variable

### ISSUE THREAD

**Issue by misalungi** [wmkhoo/taintgrind#26]
I have a project consists of several cpp files. I want to use taintgrind to track a variable. I do not know how to mention which variable to be taint. Should I make a txt file or a dat file to mention the variable and put the address of txt file in this command:
$ valgrind --tool=taintgrind --file-filter=/path/to/test.txt --taint-start=0 --taint-len=1 gzip path/to/test.txt

**Comment by wmkhoo** [comment]
That command is to taint the contents of a file. If you want to taint a variable in your program, use the client request TNT_TAINT().

**Comment by wmkhoo** [comment]
Hi,

VALGRIND_DO_CLIENT_REQUEST_STMT is defined in valgrind.h, which is part of
valgrind. Did you download and build valgrind?

Regards

**Comment by misalungi** [comment]
It works now.
Thank you!

**Comment by misalungi** [comment]
Now I created a dot file with this command:
valgrind --tool=taintgrind tests/sign32 2>&1 | python log2dot.py > sign32.dot
 I want to convert it to png or svg or pdf it gives this error:
syntax error in line 47 near '&'

**Comment by wmkhoo** [comment]
This is an ugly hack, but see if it works. I should probably use regex at some point.

**Comment by wmkhoo** [comment]
Closing this issue
