### ISSUE TITLE
Reducing the taint graph 

### ISSUE THREAD

**Issue by yasaminmahmoodi** [wmkhoo/taintgrind#29]
Hello,

I use taintgrind for SystemC project. It taints all the SystemC library modules which are used in the project. Therefore, the Graphviz file will be a big one, so that it is difficult to visualize. 
I would like to know if it is possible to only show the output of my modules in the graph.

Thank you for your help!

**Comment by wmkhoo** [comment]
I'm not familiar with any tools that work with dot files.
You could try manually reducing the graph yourself using any text editor, i.e. remove all the subgraphs you're not interested in.

**Comment by yasaminmahmoodi** [comment]
ok,
Thank you for your help.

**Comment by yasaminmahmoodi** [comment]
Hi again,

Thank you for adding head=yes option to limit propagation of tainted data. It is a great option!
It would be also great if there was an option to print output of taintgrind based on the Address/Location part. In this way we could limit the printed output based on some certain modules. 
Or if it was possible to skip printing some outputs based on Address/Location. 

Best Regards,
Yasamin

**Comment by wmkhoo** [comment]
One option is to use grep to filter the desired output, e.g.
```
$ <taintgrind command> 2>&1 | grep -E "module1|module2"
```
The above command will print only lines containing the string "module1" or "module2".
Another option is to modify the log2dot.py Python script.
