### ISSUE TITLE
Print the taintedness (tainted/untainted) of each variable

### ISSUE THREAD

**Issue by PriyankaPanigrahi** [wmkhoo/taintgrind#37]
Let in a program a variable 'x' is tainted. There is an assignment 'y=x' where y is untainted.
How to check the taintflow in the output or data flow graph ?

Any suggestions?

Thank you. Have a great day.

**Comment by wmkhoo** [comment]
I've just added a new client request: TNT_IS_TAINTED.
This allows you to read the taint bits of a variable that you specify at run-time.
Have a look at the test case tests/checktaint.c to see if this is useful for you.

If you run this test case, you should get:
`a is_tainted: ffffffff`
`b is_tainted: 00000000`
`c[0] is_tainted: 00000000`
`c[1] is_tainted: 00000000`
`c[2] is_tainted: 00000000`
`c[3] is_tainted: 00000000`
`c[4] is_tainted: 00000000`
`c[5] is_tainted: ffffffff`
`c[6] is_tainted: 00000000`
`c[7] is_tainted: ffffffff`
`c[8] is_tainted: 00000000`
`c[9] is_tainted: 00000000`

**Comment by PriyankaPanigrahi** [comment]
Thank you so much for your reply.

I feel this will help me to get the desired output.

Could you please elaborate on how to run it?
I am not getting the desired output.

Have a great day. 
Thank you.

**Comment by PriyankaPanigrahi** [comment]
How does it allow us to read the taint bits of a variable to specify at run-time?

**Comment by wmkhoo** [comment]
If you look at tests/checktaint.c, the lines that print the taint bits are:
`   TNT_IS_TAINTED(t, &a, sizeof(a));`
`   printf("a is_tainted: %08x\n", t);`

TNT_IS_TAINTED() takes 3 arguments: the output variable (unsigned int), an address, and the number of bytes to read. The taint bits will be written to t, which you can then print out.

**Comment by PriyankaPanigrahi** [comment]
I made all the changes as you suggested.

I am getting output  for various functions, such as  _itoa_word, vfprintf, _IO_file_xsputn@@GLIBC_2.2.5,  __memcpy_avx_unaligned_erms and many more. 

But not getting the desired output. I am not able to understand where I am wrong.

Please suggest.

**Comment by wmkhoo** [comment]
From what you're saying, the taintgrind output, which is written to stderr,
is getting in the way.
One way is to pipe stderr to /dev/null; another option is to save stdout to
a file, e.g. <taintgrind cmd> > output.txt.

Hope that helps.

**Comment by PriyankaPanigrahi** [comment]
> I've just added a new client request: TNT_IS_TAINTED.
> This allows you to read the taint bits of a variable that you specify at run-time.
> Have a look at the test case tests/checktaint.c to see if this is useful for you.
> 
> If you run this test case, you should get:
> `a is_tainted: ffffffff`
> `b is_tainted: 00000000`
> `c[0] is_tainted: 00000000`
> `c[1] is_tainted: 00000000`
> `c[2] is_tainted: 00000000`
> `c[3] is_tainted: 00000000`
> `c[4] is_tainted: 00000000`
> `c[5] is_tainted: ffffffff`
> `c[6] is_tainted: 00000000`
> `c[7] is_tainted: ffffffff`
> `c[8] is_tainted: 00000000`
> `c[9] is_tainted: 00000000`

Thank you so much for your help.

Does it mean: if we get. ffffffff, it means tainted and for 00000000 means untainted?

**Comment by wmkhoo** [comment]
Not just that. ffffffff means all 32 bits are tainted.

**Comment by PriyankaPanigrahi** [comment]
Thank you very much for your reply.

**Comment by wmkhoo** [comment]
Just to add that the number of bytes that TNT_IS_TAINTED can accept are: 1, 2, 4 and 8.

**Comment by PriyankaPanigrahi** [comment]
So, in place of sizeof(taintedvariable), we can mention 1, 2, 4 or 8.

**Comment by PriyankaPanigrahi** [comment]
For source code:

int main(int argc, char **argv)
{
    int a = 1000, b;
    unsigned int t;
    // Defines int a as tainted
    TNT_TAINT(&a,sizeof(a));
    
    if (a==1000)
    	b=1;
    else
    	b=0;

    TNT_IS_TAINTED(t, &a, sizeof(a));
    printf("a is_tainted: %x\n", t);

    TNT_IS_TAINTED(t, &b, sizeof(b));
    printf("b is_tainted: %x\n", t);

    return 0;
}

variable b should be tainted or not, as value of b depends on value of a?

**Comment by wmkhoo** [comment]
Let's take a similar example (http://bitblaze.cs.berkeley.edu/papers/dta%2B%2B-ndss11.pdf Fig. 3):
<pre>    char output[256];
    long input = user_input();
    long len = 0;
    if (input > 100) {
        strcpy(output, "large");
        len = 5;
    } else {
        strcpy(output, "small");
        len = 5;
    }
    print_output(output, len);</pre>
In this case, is len dependent on input?

**Comment by PriyankaPanigrahi** [comment]
Whatever the value of input, len will print 5 only. So, it is not dependent.

**Comment by wmkhoo** [comment]
There are at least three types of taint dependency. Let x be tainted.
1. Direct dependence, e.g. y = x
2. Indirect/Control-flow dependence, e.g. if(x){ y = 2; }
3. Address/Pointer dependence, e.g. y = a[x]

Taintgrind, which follows Valgrind memcheck, only implements 1, not 2 or 3. This means it will under-taint, i.e. it will miss some dependencies. On the other hand, it is tricky to handle 2 and 3, as it may lead to over-tainting, i.e. reporting dependencies where there is none.
For more info on taint analysis, check out https://users.ece.cmu.edu/~aavgerin/papers/Oakland10.pdf.

**Comment by PriyankaPanigrahi** [comment]
Thank you for your reply.

As taintgrind is under-taint, is there any other tool, which can address all the 1, 2, and 3, or there is no other tool because of over-tainting.

**Comment by wmkhoo** [comment]
Let me add that although under-tainting will miss some dependencies, it can still be useful.

Some other dynamic taint analysis tools I'm aware of, but have not tried (and the info may not be up-to-date):
1. [libdft](http://www.cs.columbia.edu/~vpk/research/libdft/): According to their paper, "in this work, we do not consider cases of implicit data flow that are in accordance with previous work on the subject". (http://nsl.cs.columbia.edu/papers/2012/libdft.vee12.pdf, Pg. 2)
2. [triton](https://github.com/JonathanSalwan/Triton): "Dynamic Taint Analysis. (DTA) aims to detect which data and instructions along an execution depend on user input. We consider direct tainting." (https://triton.quarkslab.com/files/DIMVA2018-deobfuscation-salwan-bardin-potet.pdf, Pg. 6)

If you want to experiment with and implement different taint rules, I hear that [bap](https://github.com/BinaryAnalysisPlatform/bap) will let you do that (but again, I have not tried it).

**Comment by PriyankaPanigrahi** [comment]
Thank you very much for your valuable reply.
It's a really great help.
