### ISSUE TITLE
Is the name on purpose?

### ISSUE THREAD

**Issue by ariccio** [wmkhoo/taintgrind#38]
...am I the only one? We googled it, and the image results are not something I will link 😂

**Comment by ariccio** [comment]
[if you don't get it](https://lmgtfy.com/?q=taint+grindr&t=i)

**Comment by wmkhoo** [comment]
Hi,

Pardon my ignorance, but I did not know of that association until you brought it up.
The "grind" suffix is to indicate the tool is associated with valgrind. Other valgrind tools that have the "grind" suffix, e.g. callgrind, cachegrind, helgrind etc.. The "taint" prefix is to indicate it does taint analysis.

Maybe the other valgrind tools do not suffer the same fate, but that's the truth behind the origin of the name.

**Comment by ariccio** [comment]
That's hilarious, but fantastic.
