### ISSUE TITLE
Analyzing external binaries

### ISSUE THREAD

**Issue by aug2uag** [wmkhoo/taintgrind#40]
Hello, I'm trying to analyze binary that was compiled on an external source.

Currently, I'm able to run Taintgrind successfully on binary compiled locally as follows:

something.c
```c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv){
  int i;
  int a[10];
  for (i = 0; i < 9; i++)
    a[i] = i;
    
  for (i = 0; i < 10; i++){
    printf("%d ", a[i]);
  }
  printf("\n");
  return 0;
}
```

compilation and analysis:
```
# gcc -Wall -pedantic -g something.c -o something
# /code/valgrind/build/bin/valgrind --tool=taintgrind ./something
==207== Taintgrind, the taint analysis tool
==207== Copyright (C) 2010-2018, and GNU GPL'd, by Wei Ming Khoo.
==207== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==207== Command: ./something
==207== 
0 1 2 3 4 5 6 7 8 31 
==207== 
 ```

I am unable to analyze the same compiled on another machine:
```
# /code/valgrind/build/bin/valgrind --tool=taintgrind /container_mount/something
valgrind: failed to start tool 'taintgrind' for platform 'x86-linux': No such file or directory
```

Would you please let me know if Taintgrind and/or Valgrind would support such operation or whether there's an issue you can identify in my implementation?

**Comment by wmkhoo** [comment]
There was an error in the 3.17.0 release Dockerfile. I've since updated it.
Could you see if this fixes the error?

**Comment by aug2uag** [comment]
Yes, same results.

**Comment by aug2uag** [comment]
Would anyone know if cross-compiled binary is supported by Valgrind?

**Comment by wmkhoo** [comment]
Cross-compiled binaries should be supported. What architecture/platform are
you analysing?

**Comment by aug2uag** [comment]
That's great news! I cannot get Valgrind to analyze binaries from another source. I have only tried a limited set of C files, however, all indications are there's no issue analyzing local and/or locally compiled binaries.

An example of a problematic binary is the following:

```
# file blazar
binaries/blazar: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ac1e268eb2b6e8225a6c89408e3b2aa706f8dd83, not stripped
```

**Comment by wmkhoo** [comment]
This error
```
valgrind: failed to start tool 'taintgrind' for platform 'x86-linux': No such file or directory
```
is due to valgrind not being able to locate the taintgrind tool.

What happens when you do
```
# /code/valgrind/build/bin/valgrind --tool=memcheck /container_mount/something
```

Could you also do the following:
```
# ls /code/valgrind/build/lib/
```
and
```
# ls /code/valgrind/build/libexec/
```

**Comment by aug2uag** [comment]
With memcheck it's the same:

```
# /code/valgrind/build/bin/valgrind --tool=memcheck /container_mount/something
valgrind: failed to start tool 'memcheck' for platform 'x86-linux': No such file or directory
```

Output results:

```
# ls /code/valgrind/build/lib/
pkgconfig  valgrind

# ls /code/valgrind/build/libexec/
valgrind
```

**Comment by aug2uag** [comment]
I've tried setting path first to Valgrind but same results: 
```
# export VALGRIND_LIB=/code/valgrind
# /code/valgrind/build/bin/valgrind --tool=memcheck /container_mount/something
valgrind: failed to start tool 'memcheck' for platform 'x86-linux': No such file or directory
# export VALGRIND_LIB=/code/valgrind/.in_place/
# /code/valgrind/build/bin/valgrind --tool=memcheck /container_mount/something
valgrind: failed to start tool 'memcheck' for platform 'x86-linux': No such file or directory
```

**Comment by wmkhoo** [comment]
If you're using valgrind-3.17.0, could you do the following (need to replace xxx):
```
# file /code/valgrind/build/libexec/valgrind/taintgrind-xxx
```
Otherwise do:
```
# file /code/valgrind/build/lib/valgrind/taintgrind-xxx
```
What was the architecture used to build valgrind/taintgrind?

**Comment by aug2uag** [comment]
Taintgrind Dockerfile was built with OSX 10.15.7 (19H15), I can see the file, however unable to analyze:

```
# file /code/valgrind/build/libexec/valgrind/taintgrind-amd64-linux 
/code/valgrind/build/libexec/valgrind/taintgrind-amd64-linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=eeaa63d4481402068f8621bad14b2c544fc5e63b, with debug_info, not stripped
# export VALGRIND_LIB=/code/valgrind/build/libexec/valgrind/taintgrind-amd64-linux 
# /code/valgrind/build/bin/valgrind --tool=memcheck /container_mount/something
valgrind: failed to start tool 'memcheck' for platform 'x86-linux': Not a directory
# /code/valgrind/build/bin/valgrind --tool=taintgrind /container_mount/something              
valgrind: failed to start tool 'taintgrind' for platform 'x86-linux': Not a directory
# /code/valgrind/build/libexec/valgrind/taintgrind-amd64-linux /container_mount/something 
valgrind: You cannot run '/code/valgrind/build/libexec/valgrind/taintgrind-amd64-linux' directly.
valgrind: You should use $prefix/bin/valgrind.
```

The `something` file is a simple C program that was compiled on another machine. What's interesting is I can always successfully execute on decompiled file. Is there a major difference in analyzing binary versus decompiled files? Also, if you may know, is there a method to fuzz or penetrate the vulnerabilities with Valgrind? [I noticed in the documentation it stated calls may be trapped[(https://www.valgrind.org/docs/manual/manual-core-adv.html), and I've been wanting to achieve this behavior of running the binary.

**Comment by wmkhoo** [comment]
It seems to work now.
```
$ uname -m
x86_64
$ gcc -m32 ~/test.c -o tests/test-m32
$ sudo docker run -it --rm -v $(pwd):/pwd tg /pwd/tests/test-m32
/code/valgrind/build/bin/valgrind --tool=taintgrind /pwd/tests/test-m32
==8== Taintgrind, the taint analysis tool
==8== Copyright (C) 2010-2018, and GNU GPL'd, by Wei Ming Khoo.
==8== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==8== Command: /pwd/tests/test-m32
==8== 
```

**Comment by wmkhoo** [comment]
> The `something` file is a simple C program that was compiled on another machine. What's interesting is I can always successfully execute on decompiled file. Is there a major difference in analyzing binary versus decompiled files? 

What do you mean by decompiled files?

> Also, if you may know, is there a method to fuzz or penetrate the vulnerabilities with Valgrind? [I noticed in the documentation it stated calls may be trapped[(https://www.valgrind.org/docs/manual/manual-core-adv.html), and I've been wanting to achieve this behavior of running the binary.

Vg and Tg are not meant to be fuzzers, since they only execute one path. There are decent fuzzers out there that you can try, say [AFL](https://github.com/google/AFL) or [AFL++](https://github.com/AFLplusplus/AFLplusplus). But after you have generated test cases from fuzzing, you can analyse them under Vg/Tg for memory errors or crash root-cause analysis.

**Comment by aug2uag** [comment]
Thank you for your works, informative responses, and help @wmkhoo 

Much appreciated!
