### ISSUE TITLE
Some network programs do not take effect

### ISSUE THREAD

**Issue by songxpu** [wmkhoo/taintgrind#43]
Hello, this tool is very useful for me, but recently I found that it cannot track some network programs taint, and I don’t know why.

Take this program as an example：https://github.com/hfiref0x/LightFTP  

The following is some screenshot.

You can see that taintgrind successfully started the target program
![image](https://user-images.githubusercontent.com/44093631/132948677-f4de18d6-1b1f-4a0f-b500-407a6c39d819.png)

Now I make an FTP request to the server
![image](https://user-images.githubusercontent.com/44093631/132948708-d259aac0-76d2-45d1-9e4d-40197db55b7f.png)

Let's take a look at the results now. Only the running results of the program are printed out, and there is no taint tracking information.
![image](https://user-images.githubusercontent.com/44093631/132948722-fb17f034-09fa-4692-b0d5-de3dd0e620d4.png)

Is this the cause of taintgrind?
wish you a happy life :）

**Comment by songxpu** [comment]
This program uses pthread_create to create a server. Does that mean taintgrand can't trace the stain of this multithreaded program?

**Comment by wmkhoo** [comment]
Have you tried the --trace-children=yes valgrind option? By default, it's not turned on.

**Comment by songxpu** [comment]
Hi, I added this option, but it also didn't take effect. I'm very confused.

![image](https://user-images.githubusercontent.com/44093631/132974385-d0c6890a-d2df-41a4-83ce-37c970fa9ebd.png)

A similar case is [libcoap](https://github.com/obgm/libcoap), which has a very small example.

**Comment by songxpu** [comment]
When compiling the program, the options I use are "- o0" and "- G", which should be no problem.

:)

**Comment by wmkhoo** [comment]
Tg looks for system calls recv, recvmsg and recvfrom to taint network data. Could you check if LightFTP uses any of these system calls? You could run strace.

**Comment by songxpu** [comment]
I see. Thank you very much.
:)

**Comment by songxpu** [comment]
Unfortunately, I found that lighftp uses the recvfrom system call, but taintgrand did not get the data of these FTP requests.


![image](https://user-images.githubusercontent.com/44093631/133558656-c6adcd1f-e7d9-4743-a990-264f9c4408b7.png)

**Comment by wmkhoo** [comment]
If the accept and recvfrom were done by different threads, Tg would not taint the buffer. 
The patch marks the file descriptor for all threads as tainted.

**Comment by songxpu** [comment]
Thank you very much. Now taintgrand can be used for lightftp.

**Comment by wmkhoo** [comment]
Ok great. Closing this issue.
