### ISSUE TITLE
Binary program is displayed in stain log record, not source program

### ISSUE THREAD

**Issue by songxpu** [wmkhoo/taintgrind#44]
Hello, I am using taintgrind to test [Wakaama](https://github.com/eclipse/wakaama), but found that the taint data location information obtained is not the source program: line number, but the binary program.So I am very confused.
![image](https://user-images.githubusercontent.com/44093631/135385292-0bea504f-f962-4516-9099-7b1e0096f006.png)

In fact, the function output_buffer() appears in the main function of ./wakaama/examples/server/lwm2mserver.c
![image](https://user-images.githubusercontent.com/44093631/135385366-f37723d2-be81-4cd5-a4c5-947004742f40.png)

So, what causes this phenomenon?

My command line is:
```bash
sudo ./valgrind-3.17.0/build/bin/valgrind --tool=taintgrind --taint-network=yes --trace-children=yes --log-file=/home/user/taintgrind_lwm2m.txt ./lwm2mserver

**Comment by songxpu** [comment]
Oh, I see. Do I have to add "-g" at compile time ?

**Comment by wmkhoo** [comment]
Yes. If you want to see the source file and line number.
