### ISSUE TITLE
Valgrind web link

### ISSUE THREAD

**Issue by paulfloyd** [wmkhoo/taintgrind#47]
I'm one of the Valgrind developers, and I'd like to update the web site a little.

https://valgrind.org/gallery/users.html mentions taintcheck as a CMU tool, but the link is dead.

This looks like the PDF http://bitblaze.cs.berkeley.edu/papers/taintcheck-full.pdf

Is this the same codebase? I guess not.

**Comment by wmkhoo** [comment]
No, this tool is based on Flayer (https://code.google.com/archive/p/flayer/)
and this paper
https://research.google.com/pubs/archive/33253.pdf

**Comment by paulfloyd** [comment]
OK thanks, I fixed the other broken link and added links to this project and the two other links that you provided.
